"""Reproduce correctness and scaling evidence for the complete Asian oracle."""

from __future__ import annotations

import argparse
import importlib.metadata
import math
from pathlib import Path

import numpy as np

from qc_option_pricing.quantum.asian_oracle import (
    AsianGridSpec,
    build_asian_model,
    build_asian_oracle,
    enumerate_encoded_asian,
    estimate_asian_oracle_resources,
    gauss_hermite_normal_grid,
    inverse_roundtrip_leakage_from_mps,
    objective_probability_from_mps,
)


def _fmt(value: float) -> str:
    return f"{value:.15g}"


def _stress_discrete_am_gm(seed: int = 20260713, trials: int = 250) -> tuple[int, int, int]:
    rng = np.random.default_rng(seed)
    validated = 0
    rejected_zero_payoff = 0
    minimum_residual = math.inf
    for _ in range(trials):
        first_probability = float(rng.uniform(0.05, 0.95))
        spec = AsianGridSpec(
            n_dates=int(rng.integers(2, 8)),
            shock_points=(-1.0, 1.0),
            shock_probabilities=(first_probability, 1.0 - first_probability),
            s0=float(rng.integers(2, 12)),
            strike=float(rng.integers(0, 12)),
            rate=float(rng.uniform(-0.1, 0.2)),
            volatility=float(rng.uniform(0.01, 1.2)),
            maturity=float(rng.uniform(0.1, 3.0)),
            shock_scale=1,
            price_scale=1,
        )
        try:
            reference = enumerate_encoded_asian(spec, max_paths=256)
        except ValueError as exc:
            if "identically zero" not in str(exc):
                raise
            rejected_zero_payoff += 1
            continue
        validated += 1
        minimum_residual = min(minimum_residual, reference.minimum_residual_numerator)
        if not math.isclose(
            reference.arithmetic_payoff_undiscounted,
            reference.geometric_payoff_undiscounted
            + reference.residual_payoff_undiscounted,
            rel_tol=0.0,
            abs_tol=1e-12,
        ):
            raise AssertionError("QCV decomposition failed during stress test")
    return validated, rejected_zero_payoff, int(minimum_residual)


def build_report() -> str:
    spec = AsianGridSpec(
        n_dates=2,
        shock_points=(-1.0, 1.0),
        shock_probabilities=(0.4, 0.6),
        s0=2.0,
        strike=1.0,
        rate=0.0,
        volatility=0.3,
        maturity=1.0,
        shock_scale=1,
        price_scale=1,
    )
    model = build_asian_model(spec)
    reference = enumerate_encoded_asian(model)
    raw = build_asian_oracle(model, "raw")
    qcv = build_asian_oracle(model, "qcv")
    raw_probability, raw_work_leakage = objective_probability_from_mps(raw)
    qcv_probability, qcv_work_leakage = objective_probability_from_mps(qcv)
    raw_roundtrip = inverse_roundtrip_leakage_from_mps(raw)
    qcv_roundtrip = inverse_roundtrip_leakage_from_mps(qcv)

    decomposed_raw = raw.circuit.decompose(reps=8)
    decomposed_qcv = qcv.circuit.decompose(reps=8)
    raw_ops = decomposed_raw.count_ops()
    qcv_ops = decomposed_qcv.count_ops()

    gh_points, gh_probabilities = gauss_hermite_normal_grid(2)
    gh_x = np.asarray(gh_points)
    gh_p = np.asarray(gh_probabilities)
    moments = [float(gh_p @ gh_x**degree) for degree in range(5)]
    stress_validated, stress_rejected, stress_minimum = _stress_discrete_am_gm()

    lines = [
        "# Full finite-grid Asian oracle validation",
        "",
        "Generated by `scripts/validate_full_asian_oracle.py`. All reported circuit probabilities "
        "come from the decomposed Qiskit circuit, not from the classical reference.",
        "",
        "## Environment",
        "",
        f"- Qiskit: {importlib.metadata.version('qiskit')}",
        f"- Qiskit Aer: {importlib.metadata.version('qiskit-aer')}",
        f"- NumPy: {np.__version__}",
        "- Simulator: Aer matrix-product state, analytic probabilities (`shots=None`)",
        "- Circuit decomposition basis observed here: `u`, `cx`",
        "",
        "## What the oracle actually implements",
        "",
        "Each fixing has its own independently prepared shock register. The circuit then (1) "
        "adds the signed shock into a cumulative register, (2) reversibly looks up the GBM "
        "fixing on the finite grid, (3) adds that fixing to the arithmetic total, (4) encodes "
        "the payoff probability, and (5) reverses all arithmetic and lookup work. No complete "
        "path vector is state-prepared.",
        "",
        "The QCV circuit additionally computes the weighted shock sum for the geometric average, "
        "encodes the arithmetic-minus-geometric call residual, and uncomputes it. Arithmetic "
        "fixings use ceiling fixed-point rounding while the geometric average uses floor rounding.",
        "",
        "## Exact encoded-model test",
        "",
        "Configuration: 2 dates, shocks `(-1, +1)` with probabilities `(0.4, 0.6)`, "
        "S0=2, K=1, r=0, sigma=0.3, T=1, one currency unit of price resolution.",
        "",
        "| Quantity | Classical exhaustive reference | Full circuit | Absolute error |",
        "|---|---:|---:|---:|",
        f"| Raw objective probability | {_fmt(reference.raw_objective_probability)} | "
        f"{_fmt(raw_probability)} | {_fmt(abs(raw_probability-reference.raw_objective_probability))} |",
        f"| QCV residual probability | {_fmt(reference.qcv_objective_probability)} | "
        f"{_fmt(qcv_probability)} | {_fmt(abs(qcv_probability-reference.qcv_objective_probability))} |",
        "",
        f"- Encoded arithmetic payoff E[A]: {_fmt(reference.arithmetic_payoff_undiscounted)}",
        f"- Encoded geometric control E[G]: {_fmt(reference.geometric_payoff_undiscounted)}",
        f"- Encoded residual E[A-G]: {_fmt(reference.residual_payoff_undiscounted)}",
        f"- Identity error `E[A] - E[G] - E[A-G]`: "
        f"{_fmt(reference.arithmetic_payoff_undiscounted-reference.geometric_payoff_undiscounted-reference.residual_payoff_undiscounted)}",
        f"- Minimum pathwise residual numerator over all {reference.path_count} paths: "
        f"{reference.minimum_residual_numerator}",
        f"- Raw dirty-work probability: {_fmt(raw_work_leakage)}",
        f"- QCV dirty-work probability: {_fmt(qcv_work_leakage)}",
        f"- Raw `A` then `A^-1` nonzero probability: {_fmt(raw_roundtrip)}",
        f"- QCV `A` then `A^-1` nonzero probability: {_fmt(qcv_roundtrip)}",
        "",
        "## Decomposed small-circuit counts",
        "",
        "These counts validate executability; they are not fault-tolerant T counts.",
        "",
        "| Circuit | Qubits | High-level QROM rows | QROM bit toggles | Rotations | CX | U | Depth |",
        "|---|---:|---:|---:|---:|---:|---:|---:|",
        f"| Raw | {raw.circuit.num_qubits} | {raw.lookup_rows} | {raw.lookup_bit_toggles} | "
        f"{raw.controlled_rotations} | {raw_ops.get('cx',0)} | {raw_ops.get('u',0)} | {decomposed_raw.depth()} |",
        f"| QCV | {qcv.circuit.num_qubits} | {qcv.lookup_rows} | {qcv.lookup_bit_toggles} | "
        f"{qcv.controlled_rotations} | {qcv_ops.get('cx',0)} | {qcv_ops.get('u',0)} | {decomposed_qcv.depth()} |",
        "",
        "## Distribution and invariant tests",
        "",
        "The four-node Gauss-Hermite standard-normal rule (before integer shock rounding) gives "
        "moments:",
        "",
        f"- m0={_fmt(moments[0])}, m1={_fmt(moments[1])}, m2={_fmt(moments[2])}, "
        f"m3={_fmt(moments[3])}, m4={_fmt(moments[4])}",
        "- Targets are `(1, 0, 1, 0, 3)`; the rule is exact for these moments to floating-point error.",
        f"- Random discrete AM-GM stress: {stress_validated} nonzero-payoff models passed; "
        f"{stress_rejected} identically-zero models were rejected by design.",
        f"- Lowest residual numerator observed in the stress run: {stress_minimum} (must be >= 0).",
        "",
        "## Scaling with fixing count",
        "",
        "The following is a deliberately coarse benchmark grid: one shock qubit/date with shocks "
        "±1, price scale 1, S0=K=100, r=5%, sigma=20%, T=1. Counts are logical, pre-synthesis, "
        "and omit the cost of state-preparation synthesis.",
        "",
        "| Dates | Raw qubits | QCV qubits | Raw lookup rows | QCV lookup-row upper bound | "
        "QCV residual rectangle |",
        "|---:|---:|---:|---:|---:|---:|",
    ]

    for dates in (2, 4, 8, 16, 32, 64, 128, 252):
        scale_spec = AsianGridSpec(
            n_dates=dates,
            shock_points=(-1.0, 1.0),
            shock_probabilities=(0.5, 0.5),
            s0=100.0,
            strike=100.0,
            rate=0.05,
            volatility=0.2,
            maturity=1.0,
            shock_scale=1,
            price_scale=1,
        )
        scale_model = build_asian_model(scale_spec)
        raw_estimate = estimate_asian_oracle_resources(scale_model, "raw")
        qcv_estimate = estimate_asian_oracle_resources(scale_model, "qcv")
        rectangle = (scale_model.maximum_total + 1) * (
            scale_model.weighted_max - scale_model.weighted_min + 1
        )
        lines.append(
            f"| {dates} | {raw_estimate.total_qubits:,} | {qcv_estimate.total_qubits:,} | "
            f"{raw_estimate.lookup_rows:,} | {qcv_estimate.lookup_rows:,} | {rectangle:,} |"
        )

    lines.extend(
        [
            "",
            "## Proof obligations that are met",
            "",
            "1. **No path-table loader.** The stochastic register is a tensor product of one "
            "small state preparation per fixing. Path evolution is performed after loading.",
            "2. **Exact finite-grid objective.** For payoff numerator `p` and cap `B`, the "
            "controlled rotation angle is `2 asin(sqrt(min(p/B,1)))`; hence the objective-one "
            "probability is exactly `min(p/B,1)` up to gate/simulator floating point.",
            "3. **Clean A-operator.** Work leakage and the explicit `A A^-1` test are reported above.",
            "4. **Nonnegative QCV residual.** If `s_i=ceil(scale*S_i)` and "
            "`g=floor(scale*G)`, AM-GM gives `sum_i s_i >= scale*sum_i S_i >= "
            "N*scale*G >= N*g`. Monotonicity of `max(x-NK,0)` then gives a nonnegative "
            "integer call residual path by path.",
            "5. **Exact finite-grid QCV identity.** With no cap binding, arithmetic call = "
            "geometric call + residual on every encoded path, so the same equality holds in expectation.",
            "",
            "## What is not proved—and must not be claimed",
            "",
            "- This does not establish accuracy for the continuous 252-dimensional GBM model. "
            "Shock quadrature, integer shock rounding, price rounding, any payoff cap, and AE "
            "statistical error require separate bounds or convergence studies.",
            "- The reference exponential is QROM, and the current QCV residual is a rectangular "
            "QROM. At 252 coarse fixings the QCV upper bound already exceeds 23 billion lookup "
            "rows. That is a complete oracle specification, but not a credible advantage circuit.",
            "- A publishable scaling claim needs a reversible fixed-point exponential plus "
            "comparator/subtractor payoff arithmetic, followed by Clifford+T synthesis and an "
            "end-to-end error budget. Replacing only the residual rectangle is the highest-priority "
            "engineering step.",
            "- QAE query complexity applies to calls to this A-operator. It does not make the "
            "per-call arithmetic, state preparation, fault-tolerant synthesis, or data movement free.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("results/v5/full_asian_oracle_validation.md"),
    )
    args = parser.parse_args()
    report = build_report()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(report, encoding="utf-8")
    print(report)
    print(f"\nWrote {args.output}")


if __name__ == "__main__":
    main()
